### ISSUE TITLE
PAM.authenticate should allow for mock returns

### ISSUE THREAD

**Issue by busbey** [kohsuke/libpam4j#1]
Hi!

I'm trying to make use of this library within Spring Security. It's been awesomely easy.

One issue I've run into is that UnixUser's final class modifier makes it so I can mock it via Mockito. This makes it so I essentially can't test my code's use of the library without having access to an actual pam service.

Any chance you could make it non-final?

**Comment by siva-chandrasekaran** [comment]
Hi Busbey - Do you have a sample code to use PAM authenticate with Spring Security? Thanks!

**Comment by busbey** [comment]
Nope. Haven't looked at any of the PAM stuff in ~3 years.
