### ISSUE TITLE
pam_tally2 does not reset tally on successful login

### ISSUE THREAD

**Issue by NilSet** [kohsuke/libpam4j#14]
When the PAM module pam_tally2 is in use, it tallies the login attempts, in order to lock out accounts after a sequence of consecutive failed attempts. It is supposed to reset the count after a successful login, but it uses calls to `pam_setcred` to know that the full PAM stack succeeded in `pam_authenticate`, and libpam4j does not call this.

**Comment by robrez** [comment]
Ran into this issue. Would you consider making a new patch release?

http://mvnrepository.com/artifact/org.kohsuke/libpam4j
