### ISSUE TITLE
Inconsistent "getGroups()" and garbage getShell() results under load

### ISSUE THREAD

**Issue by jamshid** [kohsuke/libpam4j#9]
When I run the test program https://gist.github.com/jamshid/8776435 (written for another bug) I get inconsistent results from getGroups() and sometimes some corruption in the getShell() result. Tested on CentOS 6.5 and Ubuntu 13.

I added the user gw-john with:

```
# groupadd gw-admin
# useradd gw-john --groups gw-admin -M
# echo gw-john:password | chpasswd
```

The program starts 1000 threads doing PAM.authenticate() and outputs the user's info, but many of the results do _not_ list the gw-admin group and there's even some garbage (seen on Ubuntu 13). Btw I usually get the inconsistent groups even with 10 threads.

Any ideas? I guess I should try a non-java version to see if it's reproducible.

```
$ sudo java -classpath ./jna-3.5.2.jar:./libpam4j-1.7.jar:. PamTest 1000 | grep User  | sort | uniq
User gw-john 1001 1004 /home/gw-john  /bin/sh in [gw-admin]
User gw-john 1001 1004 /home/gw-john  /bin/sh in [gw-admin, gw-john]
User gw-john 1001 1004 /home/gw-john  /bin/sh in [gw-john]
User gw-john 1001 1004 /home/gw-john  /bin/sh in [operatorx, gw-john]
User gw-john 1001 1004 /home/gw-john  /dbus:/bise/shvar/lib/gnats/bin/sh in [gw-admin, gw-john]
```

**Comment by matthiasblaesing** [comment]
I pushed a potential fix into a branch, that should fix this. I'm not sure whether my assumptions with regard to the memory sizes are sound, but it should work. The testsuite completes.

**Comment by jamshid** [comment]
Thank you @kohsuke and @matthiasblaesing! 

This will be released to maven repos as org.kohsuke libpam4j 1.10?
